name: Schedule Telegram Posts

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create required files
        run: |
          mkdir -p images
          [ -f input.txt ] || echo "Тестовый промпт" > input.txt

      - name: Run Telegram bot
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python telegram_bot.py
          cat combined_app.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debug-data
          path: |
            combined_app.log
            images/
            input.txt
            image_prompts.txt

      - name: Update input file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add input.txt
          git diff --cached --quiet || git commit -m "Update input.txt"
          git push