name: Schedule Telegram Posts

on:
  workflow_dispatch:
 # schedule:
   # - cron: '30 * * * *'  # Каждый час в 30 минут

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create required files
        run: |
          mkdir -p images
          if [ ! -f input.txt ]; then
            echo "Тестовый промпт" > input.txt
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram bot
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python telegram_bot.py
          echo "=== Bot logs ==="
          cat combined_app.log || echo "No log file found"

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bot-debug-data
          path: |
            combined_app.log
            images/
            input.txt
            image_prompts.txt
          retention-days: 1

      - name: Update processed prompts
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add input.txt
          
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto: Update processed prompts [skip ci]"
            git push
          fi
